### ISSUE TITLE
forum: discourse for meta/volunteering discussions?

### ISSUE THREAD

**Issue by guaka** [Trustroots/community#20]
_use this issue description as a wiki page_

----------------------

## pros

- good forum software
- _add more_

## cons

- another account
- 3rd party software, won't integrate
- _add more_
## questions

- is it possible to enforce logging in with trustroots account? is it feasible?
- can we get it for free? only 50% discount with at discourse.com
- would someone want to host and maintain it for us, for free-ish?
- use it for volunteering activity only? or for everything including tribe discussions etc?

**Comment by guaka** [comment]
some mentions of discourse:

## @simison Oct 13th

https://trustroots.slack.com/archives/D08SHP0P9/p1539447771000100
I’m a bit torn if to have all the code for a feature like that custom or rely on something like Discourse (which is very extensible).

Latter gives a lot of stuff for free, but gets quickly very complicated to integrate.

Probably because YAGNI (https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it), I’d go with custom code in our db.


## @regenwasser Sep 10

https://github.com/Trustroots/trustroots/issues/681#issuecomment-419929865

## @chreekat  Sep 3

https://trustroots.slack.com/archives/C08SENA9Z/p1536002325000100?thread_ts=1535877424.000100

**Comment by simison** [comment]
> I’m a bit torn if to have all the code for a feature like that custom or rely on something like Discourse (which is very extensible).

Might be worth doing a quick and simple experiment to see how it integrates, though.

**Comment by nicksellen** [comment]
In the linked thread @simison said:

> let’s try to keep TR the platform (tribes) and TR the volunteering work discussions (slack) separate

I would second this (but maybe too late already, I think this thread is about both things already maybe!). To me the idea of discourse is for off-platform discussions _about_ things concerning the trustroots platform, not _part of_ the trustroots platform.

I am generally not in favour of integrating third-party discussions platforms into custom software. My feeling is it gets messy very quickly, and hard to maintain. I don't know of any good examples of it, but also did not look very hard. Would be interested if someone has a good example?

**Comment by nicksellen** [comment]
> I'm suspicious even about the maintenance part, especially if it's something that integrates with Trustroots (and isn't just separate instance with its own accounts). Updating is one thing, keeping up with compatibility between the two systems is another.

Yup, everything I said is on the basis that it's a standalone independent vanilla discourse installation.

**Comment by Regenwasser** [comment]
But I agree with @nicksellen and @simison that we should keep volunteering and the broader community separate. However, I still think there would be value in creating a platform for user feedback and communication.

The thing is, this is usually difficult as someone has to go through that all - and be responsible to constantly interact with people and tell them our stance on issues (that we sometimes even have to discuss before) or just answer question. Which is why I rather would like to setup a feedback program to include more user voices instead of a public forum about it. Reddit/FB is enough for users to discuss meta things. 

I think this suggestion by @guaka doesn't necessarily mean that we do a "volunteering for everyone" forum. Or was this the idea? I guess it still could be the same like it is now, but just another platform.

Integrate Trustroots login with discourse, so people who want to volunteer can easily join our volunteering group where all discussions would happen (The advantage here is that volunteers don't have to sign up on Github and Slack at the same time - and where certain volunteering might be easier to manage VS a Slack with random google documents and links to Github). 

The advantage is more structure and everything at the same place. Not two repos, not a lot of dev "noise" in between.

> My feeling is it gets messy very quickly, and hard to maintain. I don't know of any good examples of it, but also did not look very hard. Would be interested if someone has a good example?

Some here probably: https://www.discourse.org/customers 

I'd also be for that: 

> let’s try to keep TR the platform (tribes) and TR the volunteering work discussions (slack) separate

**Comment by guaka** [comment]
I updated the issue title to reflect that we only consider DIscourse for volunteering discussions, not for tribe discussions.

This the ansible issue: https://github.com/Trustroots/trustroots/issues/221

**Comment by chreekat** [comment]
Adding notes on my experience:

We have a discourse open to the world (community.snowdrift.coop) that uses
our main platform for single sign-on (SSO).

The SSO implementation is pretty short, and for a mainstream language like
JavaScript, I bet there's already a library. The maintenance burden on the
platform is therefore near zero, and we can easily associate platform users
with discourse users.

Within discourse, we have a restricted section for team members. This
basically takes the place of Slack for our team (although we also use IRC
and Mumble). The restricted section and its membership is all managed from
within discourse. Imho, discourse has more potential for engaged, on-topic
discussion than Slack, thanks to its much more sophisticated moderation
tools -- particularly things like splitting threads into new topics!

Trustroots has already put a lot of energy into slack, however, so I don't
think converting to discourse would be wise unless there was a pressing
need for it.

Maintaining an open forum would indeed be a heavy ongoing burden, due to
the need to moderate. Who would be available and well trained for it?

Maintaining discourse itself is "easy" thanks to the official releases
generally being high quality. Upgrades can be managed from within discourse.

Some plugins require mucking around on the server terminal to install.

Discourse is a big ugly pile of Ruby/docker/shell scripts that I would hate
to maintain. Fingers crossed that the upstream project is robust and long
lived.

For snowdrift, switching to discourse was worth it. But our community is an
order of magnitude smaller than trustroots.

**Comment by guaka** [comment]
Thanks, @chreekat. Good to know.

Note that I didn't propose to replace Slack with Discourse (not anytime soon at least). I just feel that some discussions are better off elsewhere (not on Slack or GitHub).

**Comment by chreekat** [comment]
Gotcha, thanks for clarifying the discussion. :) Not that you were unclear to begin with! I mentioned the Slack-Discourse connection only because it makes sense to *me* that they share the same strategic purpose, and if I were building a community from scratch, I would start with Discourse. I totally agree that some discussions are better off elsewhere than Slack or Github. I apologize if my early-morning brain dump was a bit off topic, and I hope it provokes an improved understanding of the tradeoffs if we decide to go for it. :)

**Comment by guaka** [comment]
https://meta.trustroots.org/

we have this now, and all good so far :)
