### ISSUE TITLE
Change URL

### ISSUE THREAD

**Issue by Lemoert** [Trustroots/community#50]
Create a new https://www.trustroots.org/support_trustroots or something that sounds better and delete https://www.trustroots.org/donate

**Comment by hlibbabii** [comment]
https://www.trustroots.org/contribute as an option? Or is it a bit misleading?

**Comment by simison** [comment]
> /contribute as an option? Or is it a bit misleading?

I think it's fine 👍 

Other ideas:
- _Help_
- _Support Trustroots_ (and change current "support" pages to "contact us" or "get help")

**Comment by simison** [comment]
When we _actually_ take donations, it likely is most effective and clear to have an actual "donate" link in menus and headers, since that's what people are seeking for mainly.

I understand that you'd like to change current donate pages more as proxy to funnel folks into volunteering, hence the rename?
